
deploy-cicd: ## Deploy the CICD module
	@$(ENV_PATH)utility-functions.sh exec_cf_for_env cicd

destroy-cicd: ## Destroy the CICD module
	@$(ENV_PATH)utility-functions.sh destroy_root_cf_stack_by_name cicd