# Start wizard that will auto-generate IaC deployment instructions
generate-deployment-instructions:  ## Wizard to auto-generate IaC deployment instructions
	@$(ENV_PATH)generate-deployment-instructions.sh "$(b)"

# Simple generate-deployment-instructions shortcut
gdi: generate-deployment-instructions  ## Wizard to auto-generate IaC deployment instructions

